atharva:
  firstname: Atharva
  lastname: Mashalkar
  password: atash@212000
atharva21:
  firstname: Atharva
  lastname: Mashalkar
  password: atash@12000
cookie:
  expiry_days: 1
  key: 7d9f85b9-ae85-4e69-8f2d-7e3d2c4a5b1a
  name: streamlit_auth_cookie
credentials:
  usernames:
    testuser:
      name: Test User
      password: $2b$12$buD2OS6X9TkYlKJynVARjO2Y8NiH39hAXhTxHIqXcRqTy2HQ6Ysh.
preauthorized:
  emails: []
